### PR TITLE
Wd validation

### LINKED ISSUE #22: Make Validation page group profiles by platform
Ex. Win 2016 should be a single box, with three links, one each for ARS 3.1 Low/ ARS 3.1 Moderate/ ARS 3.1 High overlays.

### PR DESCRIPTION
**Pull request by wdower**
Resolves #22 

Goal is to refactor validation page to make profile links clearer. Make it easy to find low/mod/high profiles, etc.

### CODE REVIEW

**Comment by wdower** [comment]
@ejaronne @aaronlippold Changed layout as per discussion today. I'll figure out how it should look in mobile view.

**Comment by ejaronne** [comment]
More refinements:
Reorder from top to bottom:

- Cloud Service Providers
- Operating Systems
- Databases
- Application Logic
- Web Servers

Correct typo "AWS CIS Infrastructure" to read "AWS CIS **_RDS_** Infrastructure"

Narrow the 3 right columns to be equal size just a little bigger than the ARS 3.1 Moderate tile.
Second column from left for platform type: use space gained to help prevent ensure no wrapping!

For each platform row, highlight/box somehow to see keep one's eye aligned from left to right:
image

**Comment by wdower** [comment]
@ejaronne Made changes as per your comments last Friday. Also added a mobile view that's just a simple column of links. Thanks!

**Comment by ejaronne** [comment]
Nice! Some final(?) touches:
image

**Comment by ejaronne** [comment]
Almost there! Please reduce the top and bottom padding for the "grey" rows by 50%.
Also, reduce the right-hand padding by about 50%.
(trying to tighten-up the height/width a little)

**Comment by wdower** [comment]
@ejaronne Tightened up margins/padding.

**Comment by aaronlippold** [comment]
The break points here need a bit of work

also we should add a slight border to make sure the buttons don't bleed into the background.

Dark mode also needs the background toned down on the background color as it is a bit bright.

Screen Shot 2020-05-06 at 10 30 07 AM

**Comment by aaronlippold** [comment]
https://material.io/design/color/dark-theme.html#properties

The above should give you good guidance on how things should be ''colored" to look good in dark mode.

Screen Shot 2020-05-06 at 10 33 57 AM

**Comment by aaronlippold** [comment]
See here: https://myaurapp.web.app/team how the light and dark mode doesn't seem to 'yell' the colors at you.

**Comment by wdower** [comment]
Fixed the breakpoints to go to column view earlier to stop the profile chips from squishing each other. Made dark mode components progress from black to lighter shades of grey at higher elevations. In light mode I just put an outline around the chips since playing with shades of grey didn't look as good in that mode (and chips don't let you add a background color and an outline at the same time).

**Comment by ejaronne** [comment]
Looks good to me!

**Pull request merged**
